const vocabularyData = {
  Animals: [
    ["Dog","Perro","/dog/"], ["Cat","Gato","/kat/"], ["Bird","Pájaro","/berd/"], ["Fish","Pez","/fish/"], ["Mouse","Ratón","/maus/"],
    ["Horse","Caballo","/jors/"], ["Cow","Vaca","/cau/"], ["Pig","Cerdo","/pig/"], ["Sheep","Oveja","/ship/"], ["Chicken","Pollo","/chi-ken/"],
    ["Duck","Pato","/dak/"], ["Goat","Cabra","/gout/"], ["Rabbit","Conejo","/ra-bit/"], ["Frog","Rana","/frog/"], ["Turtle","Tortuga","/ter-tol/"],
    ["Snake","Serpiente","/snéik/"], ["Lizard","Lagartija","/li-zard/"], ["Bear","Oso","/ber/"], ["Lion","León","/lai-on/"], ["Tiger","Tigre","/tai-ger/"],
    ["Elephant","Elefante","/e-le-fant/"], ["Monkey","Mono","/mon-ki/"], ["Giraffe","Jirafa","/yi-raf/"], ["Zebra","Cebra","/zi-bra/"], ["Kangaroo","Canguro","/kan-ga-ro/"],
    ["Wolf","Lobo","/wolf/"], ["Fox","Zorro","/foks/"], ["Deer","Venado","/dir/"], ["Bat","Murciélago","/bat/"], ["Owl","Búho","/aul/"],
    ["Eagle","Águila","/i-gol/"], ["Spider","Araña","/spai-der/"], ["Ant","Hormiga","/ant/"], ["Bee","Abeja","/bi/"], ["Butterfly","Mariposa","/ba-ter-flai/"],
    ["Dolphin","Delfín","/dol-fin/"], ["Whale","Ballena","/weill/"], ["Shark","Tiburón","/shark/"], ["Penguin","Pingüino","/pen-güin/"], ["Seal","Foca","/sil/"],
    ["Octopus","Pulpo","/oc-to-pus/"], ["Crab","Cangrejo","/krab/"], ["Snail","Caracol","/sneil/"], ["Worm","Gusano","/uorm/"], ["Fly","Mosca","/flai/"],
    ["Mosquito","Mosquito","/mos-ki-to/"], ["Rooster","Gallo","/rus-ter/"], ["Turkey","Pavo","/ter-ki/"], ["Camel","Camello","/ka-mel/"], ["Panda","Panda","/pan-da/"]
  ],
  Fruits: [
    ["Apple","Manzana","/a-pol/"], ["Banana","Plátano","/ba-na-na/"], ["Orange","Naranja","/o-ranch/"], ["Grape","Uva","/greip/"], ["Strawberry","Fresa","/stro-be-ri/"],
    ["Lemon","Limón","/le-mon/"], ["Melon","Melón","/me-lon/"], ["Watermelon","Sandía","/wa-ter-me-lon/"], ["Pineapple","Piña","/pai-na-pol/"], ["Mango","Mango","/man-go/"],
    ["Peach","Durazno","/pich/"], ["Pear","Pera","/per/"], ["Cherry","Cereza","/che-ri/"], ["Plum","Ciruela","/plom/"], ["Kiwi","Kiwi","/ki-ui/"],
    ["Papaya","Papaya","/pa-pa-ya/"], ["Coconut","Coco","/co-co-not/"], ["Avocado","Aguacate","/a-vo-ca-do/"], ["Tomato","Tomate","/to-mei-to/"], ["Potato","Papa","/po-tei-to/"],
    ["Onion","Cebolla","/o-nion/"], ["Garlic","Ajo","/gar-lik/"], ["Carrot","Zanahoria","/ka-rot/"], ["Corn","Maíz","/corn/"], ["Lettuce","Lechuga","/le-tus/"],
    ["Broccoli","Brócoli","/bro-co-li/"], ["Spinach","Espinaca","/spi-nach/"], ["Celery","Apio","/se-le-ri/"], ["Cucumber","Pepino","/kiu-com-ber/"], ["Pepper","Pimiento","/pe-per/"],
    ["Mushroom","Champiñón","/mash-rum/"], ["Pea","Chícharo","/pi/"], ["Bean","Frijol","/bin/"], ["Cabbage","Col/Repollo","/ca-bach/"], ["Pumpkin","Calabaza","/pomp-kin/"],
    ["Zucchini","Calabacín","/zu-ki-ni/"], ["Eggplant","Berenjena","/eg-plant/"], ["Radish","Rábano","/ra-dish/"], ["Beet","Remolacha","/bit/"], ["Asparagus","Espárragos","/as-pa-ra-gus/"],
    ["Olive","Aceituna","/o-liv/"], ["Nut","Nuez","/not/"], ["Almond","Almendra","/al-mond/"], ["Peanut","Cacahuate","/pi-not/"], ["Blueberry","Mora azul","/blu-be-ri/"],
    ["Raspberry","Frambuesa","/ras-be-ri/"], ["Blackberry","Zarzamora","/blak-be-ri/"], ["Fig","Higo","/fig/"], ["Lime","Lima/Limón verde","/laim/"], ["Guava","Guayaba","/gua-va/"]
  ],
  Objects: [
    ["Book","Libro","/buk/"], ["Pen","Pluma/Bolígrafo","/pen/"], ["Pencil","Lápiz","/pen-sil/"], ["Paper","Papel","/pei-per/"], ["Notebook","Cuaderno","/nout-buk/"],
    ["Desk","Escritorio","/desk/"], ["Chair","Silla","/cher/"], ["Table","Mesa","/tei-bol/"], ["Computer","Computadora","/com-piu-ter/"], ["Phone","Teléfono","/foun/"],
    ["Bag","Bolsa/Mochila","/bag/"], ["Wallet","Cartera","/ua-let/"], ["Keys","Llaves","/kis/"], ["Glasses","Lentes","/gla-ses/"], ["Watch","Reloj de pulsera","/uatch/"],
    ["Clock","Reloj de pared","/klok/"], ["Shoes","Zapatos","/shus/"], ["Shirt","Camisa","/shert/"], ["Pants","Pantalones","/pants/"], ["Dress","Vestido","/dres/"],
    ["Jacket","Chamarra/Chaqueta","/ya-ket/"], ["Coat","Abrigo","/cout/"], ["Hat","Sombrero","/jat/"], ["Socks","Calcetines","/soks/"], ["Gloves","Guantes","/glovs/"],
    ["Umbrella","Paraguas","/om-bre-la/"], ["Ring","Anillo","/ring/"], ["Necklace","Collar","/nek-las/"], ["Earrings","Aretes","/i-rings/"], ["Belt","Cinturón","/belt/"],
    ["Bottle","Botella","/bo-tol/"], ["Cup","Taza","/kop/"], ["Glass","Vaso","/glas/"], ["Plate","Plato","/pleit/"], ["Fork","Tenedor","/fork/"],
    ["Knife","Cuchillo","/naif/"], ["Spoon","Cuchara","/spun/"], ["Napkin","Servilleta","/nap-kin/"], ["Towel","Toalla","/ta-uel/"], ["Soap","Jabón","/soup/"],
    ["Toothbrush","Cepillo de dientes","/tuz-brosh/"], ["Toothpaste","Pasta de dientes","/tuz-peist/"], ["Comb","Peine","/koum/"], ["Brush","Cepillo","/brosh/"], ["Mirror","Espejo","/mi-ror/"],
    ["Scissors","Tijeras","/si-zors/"], ["Tape","Cinta","/teip/"], ["Glue","Pegamento","/glu/"], ["Box","Caja","/boks/"], ["Basket","Canasta","/bas-ket/"],
    ["Trash can","Bote de basura","/trash kan/"], ["Broom","Escoba","/brum/"], ["Mop","Trapeador","/mop/"], ["Bucket","Cubeta","/bo-ket/"], ["Sponge","Esponja","/sponch/"],
    ["Iron","Plancha","/ai-ron/"], ["Washing machine","Lavadora","/ua-shing ma-shin/"], ["Dryer","Secadora","/drai-er/"], ["Fan","Ventilador","/fan/"], ["Heater","Calentador","/ji-ter/"],
    ["Television","Televisión","/te-le-vi-shon/"], ["Radio","Radio","/rei-di-o/"], ["Camera","Cámara","/ca-me-ra/"], ["Picture","Foto/Cuadro","/pik-cher/"], ["Painting","Pintura","/pein-ting/"],
    ["Letter","Carta","/le-ter/"], ["Stamp","Estampilla","/stamp/"], ["Envelope","Sobre","/en-ve-loup/"], ["Magazine","Revista","/ma-ga-zin/"], ["Newspaper","Periódico","/nius-pei-per/"],
    ["Map","Mapa","/map/"], ["Ticket","Boleto/Entrada","/ti-ket/"], ["Money","Dinero","/mo-ni/"], ["Coin","Moneda","/koin/"], ["Bill","Billete/Cuenta","/bil/"],
    ["Credit card","Tarjeta de crédito","/cre-dit kard/"], ["Receipt","Recibo","/ri-sit/"], ["Medicine","Medicina","/me-di-sin/"], ["Pill","Pastilla","/pil/"], ["Bandage","Vendaje/Curita","/ban-dich/"],
    ["Mask","Mascarilla","/mask/"], ["Perfume","Perfume","/per-fium/"], ["Makeup","Maquillaje","/meik-op/"], ["Lipstick","Lápiz labial","/lip-stik/"], ["Jewelry","Joyería","/yiul-ri/"],
    ["Toy","Juguete","/toi/"], ["Doll","Muñeca","/dol/"], ["Ball","Pelota","/bol/"], ["Bicycle","Bicicleta","/bai-si-kol/"], ["Car","Coche","/kar/"],
    ["Bus","Autobús","/bos/"], ["Train","Tren","/trein/"], ["Airplane","Avión","/er-plein/"], ["Boat","Barco","/bout/"], ["Ship","Buque","/ship/"],
    ["Motorcycle","Motocicleta","/mo-tor-sai-kol/"], ["Truck","Camión","/trok/"], ["Wheel","Rueda","/uil/"], ["Engine","Motor","/en-yin/"], ["Gasoline","Gasolina","/ga-so-lin/"]
  ],
  House: [
    ["House","Casa","/jaus/"], ["Apartment","Departamento","/a-part-ment/"], ["Room","Habitación","/rum/"], ["Living room","Sala","/li-ving rum/"], ["Dining room","Comedor","/dai-ning rum/"],
    ["Kitchen","Cocina","/ki-chen/"], ["Bathroom","Baño","/baz-rum/"], ["Bedroom","Recámara","/bed-rum/"], ["Garage","Cochera","/ga-rash/"], ["Garden","Jardín","/gar-den/"],
    ["Yard","Patio","/yard/"], ["Roof","Techo","/ruf/"], ["Ceiling","Techo (interior)","/si-ling/"], ["Floor","Piso","/flor/"], ["Wall","Pared","/uol/"],
    ["Door","Puerta","/dor/"], ["Window","Ventana","/güin-dou/"], ["Stairs","Escaleras","/sters/"], ["Balcony","Balcón","/bal-co-ni/"], ["Basement","Sótano","/beis-ment/"],
    ["Attic","Ático","/a-tik/"], ["Fence","Cerca/Reja","/fens/"], ["Gate","Puerta (exterior)","/geit/"], ["Pool","Alberca","/pul/"], ["Hallway","Pasillo","/jol-uei/"],
    ["Closet","Armario","/klo-set/"], ["Drawer","Cajón","/dro-er/"], ["Shelf","Estante","/shelf/"], ["Bed","Cama","/bed/"], ["Mattress","Colchón","/ma-tres/"],
    ["Blanket","Cobija","/blan-ket/"], ["Pillow","Almohada","/pi-lou/"], ["Sheet","Sábana","/shit/"], ["Rug","Alfombra pequeña","/rog/"], ["Carpet","Alfombra","/kar-pet/"],
    ["Curtain","Cortina","/ker-tain/"], ["Blinds","Persianas","/blainds/"], ["Lamp","Lámpara","/lamp/"], ["Light","Luz","/lait/"], ["Switch","Interruptor","/suitch/"],
    ["Plug","Enchufe","/plog/"], ["Sink","Fregadero/Lavabo","/sink/"], ["Toilet","Inodoro","/toi-let/"], ["Shower","Regadera","/shau-er/"], ["Bathtub","Tina","/baz-tob/"],
    ["Refrigerator","Refrigerador","/ri-fri-ye-rei-tor/"], ["Oven","Horno","/o-ven/"], ["Stove","Estufa","/stouv/"], ["Microwave","Microondas","/mai-kro-ueiv/"], ["Dishwasher","Lavaplatos","/dish-ua-sher/"]
  ],
  Food: [
    ["Food","Comida","/fud/"], ["Water","Agua","/wa-ter/"], ["Drink","Bebida","/drink/"], ["Juice","Jugo","/yus/"], ["Milk","Leche","/milk/"],
    ["Coffee","Café","/co-fi/"], ["Tea","Té","/ti/"], ["Beer","Cerveza","/bir/"], ["Wine","Vino","/uain/"], ["Soda","Refresco","/so-da/"],
    ["Bread","Pan","/bred/"], ["Butter","Mantequilla","/bo-ter/"], ["Cheese","Queso","/chis/"], ["Egg","Huevo","/eg/"], ["Meat","Carne","/mit/"],
    ["Chicken","Pollo","/chi-ken/"], ["Beef","Carne de res","/bif/"], ["Pork","Cerdo (carne)","/pork/"], ["Fish","Pescado","/fish/"], ["Seafood","Mariscos","/si-fud/"],
    ["Rice","Arroz","/rais/"], ["Pasta","Pasta","/pas-ta/"], ["Noodles","Fideos","/nu-dols/"], ["Soup","Sopa","/sup/"], ["Salad","Ensalada","/sa-lad/"],
    ["Sandwich","Sándwich","/sand-uich/"], ["Hamburger","Hamburguesa","/jam-ber-ger/"], ["Pizza","Pizza","/pit-za/"], ["Hot dog","Hot dog","/jot dog/"], ["Taco","Taco","/ta-co/"],
    ["Cereal","Cereal","/si-rial/"], ["Oatmeal","Avena","/out-mil/"], ["Pancake","Hot cake","/pan-keik/"], ["Waffle","Waffle","/wa-fol/"], ["Cake","Pastel","/keik/"],
    ["Cookie","Galleta","/ku-ki/"], ["Pie","Pay/Tarta","/pai/"], ["Ice cream","Helado","/ais-krim/"], ["Chocolate","Chocolate","/cho-co-leit/"], ["Candy","Dulce","/kan-di/"],
    ["Sugar","Azúcar","/shu-gar/"], ["Salt","Sal","/solt/"], ["Pepper","Pimienta","/pe-per/"], ["Oil","Aceite","/oil/"], ["Vinegar","Vinagre","/vi-ne-gar/"],
    ["Sauce","Salsa","/sos/"], ["Jam","Mermelada","/yam/"], ["Honey","Miel","/jo-ni/"], ["Breakfast","Desayuno","/brek-fast/"], ["Lunch","Almuerzo","/lonch/"], ["Dinner","Cena","/di-ner/"]
  ],
  Family: [
    ["Family","Familia","/fa-mi-li/"], ["Mother","Madre/Mamá","/mo-der/"], ["Father","Padre/Papá","/fa-der/"], ["Son","Hijo","/son/"], ["Daughter","Hija","/do-ter/"],
    ["Brother","Hermano","/bro-der/"], ["Sister","Hermana","/sis-ter/"], ["Grandmother","Abuela","/grand-mo-der/"], ["Grandfather","Abuelo","/grand-fa-der/"], ["Grandparents","Abuelos","/grand-pa-rents/"],
    ["Grandson","Nieto","/grand-son/"], ["Granddaughter","Nieta","/grand-do-ter/"], ["Aunt","Tía","/ant/"], ["Uncle","Tío","/on-col/"], ["Niece","Sobrina","/nis/"],
    ["Nephew","Sobrino","/ne-fiu/"], ["Cousin","Primo/Prima","/co-sin/"], ["Wife","Esposa","/uaif/"], ["Husband","Esposo","/jas-band/"], ["Parents","Padres","/pa-rents/"],
    ["Children","Niños/Hijos","/chil-dren/"], ["Baby","Bebé","/bei-bi/"], ["Man","Hombre","/man/"], ["Woman","Mujer","/u-man/"], ["Boy","Niño","/boi/"],
    ["Girl","Niña","/gerl/"], ["Friend","Amigo/Amiga","/frend/"], ["People","Gente","/pi-pol/"], ["Person","Persona","/per-son/"], ["Neighbor","Vecino","/nei-bor/"],
    ["Boss","Jefe","/bos/"], ["Colleague","Colega","/co-lig/"], ["Teacher","Maestro","/ti-cher/"], ["Student","Estudiante","/stu-dent/"], ["Doctor","Doctor","/doc-tor/"],
    ["Nurse","Enfermera","/ners/"], ["Police","Policía","/po-lis/"], ["Driver","Chofer","/drai-ver/"], ["Worker","Trabajador","/wor-ker/"], ["Manager","Gerente","/ma-na-yer/"]
  ],
  Nature: [
    ["Sun","Sol","/son/"], ["Moon","Luna","/mun/"], ["Star","Estrella","/star/"], ["Sky","Cielo","/skai/"], ["Cloud","Nube","/claud/"],
    ["Rain","Lluvia","/rein/"], ["Snow","Nieve","/snou/"], ["Wind","Viento","/uind/"], ["Storm","Tormenta","/storm/"], ["Lightning","Relámpago","/lait-ning/"],
    ["Earth","Tierra","/erz/"], ["World","Mundo","/world/"], ["Water","Agua","/ua-ter/"], ["Fire","Fuego","/fai-er/"], ["Air","Aire","/er/"],
    ["Tree","Árbol","/tri/"], ["Flower","Flor","/flau-er/"], ["Grass","Pasto","/gras/"], ["Plant","Planta","/plant/"], ["Leaf","Hoja","/lif/"],
    ["Forest","Bosque","/fo-rest/"], ["Mountain","Montaña","/maun-tain/"], ["Hill","Colina","/jil/"], ["River","Río","/ri-ver/"], ["Lake","Lago","/leik/"],
    ["Ocean","Océano","/o-shan/"], ["Sea","Mar","/si/"], ["Beach","Playa","/bich/"], ["Sand","Arena","/sand/"], ["Rock","Roca/Piedra","/rok/"],
    ["City","Ciudad","/si-ti/"], ["Town","Pueblo","/taun/"], ["Street","Calle","/strit/"], ["Road","Camino","/roud/"], ["Bridge","Puente","/brich/"],
    ["Park","Parque","/park/"], ["School","Escuela","/skul/"], ["Hospital","Hospital","/jos-pi-tal/"], ["Store","Tienda","/stor/"], ["Market","Mercado","/mar-ket/"],
    ["Restaurant","Restaurante","/res-to-rant/"], ["Bank","Banco","/bank/"], ["Church","Iglesia","/cherch/"], ["Airport","Aeropuerto","/er-port/"], ["Station","Estación","/stei-shon/"],
    ["Museum","Museo","/miu-zi-um/"], ["Library","Biblioteca","/lai-bre-ri/"], ["Movie theater","Cine","/mu-vi zi-a-ter/"], ["Gym","Gimnasio","/yim/"], ["Hotel","Hotel","/jou-tel/"]
  ],
  Adjectives: [
    ["Good","Bueno","/gud/"], ["Bad","Malo","/bad/"], ["Big","Grande","/big/"], ["Small","Pequeño","/smol/"], ["Tall","Alto","/tol/"],
    ["Short","Corto/Bajo","/short/"], ["Long","Largo","/long/"], ["Hot","Caliente","/jot/"], ["Cold","Frío","/kould/"], ["Warm","Tibio/Cálido","/uorm/"],
    ["New","Nuevo","/niu/"], ["Old","Viejo","/ould/"], ["Young","Joven","/yong/"], ["Fast","Rápido","/fast/"], ["Slow","Lento","/slou/"],
    ["Hard","Duro/Difícil","/jard/"], ["Soft","Suave","/soft/"], ["Easy","Fácil","/i-zi/"], ["Difficult","Difícil","/di-fi-colt/"], ["Heavy","Pesado","/je-vi/"],
    ["Light","Ligero/Luz","/lait/"], ["Dark","Oscuro","/dark/"], ["Bright","Brillante","/brait/"], ["Beautiful","Hermoso","/biu-ti-ful/"], ["Ugly","Feo","/og-li/"],
    ["Happy","Feliz","/ja-pi/"], ["Sad","Triste","/sad/"], ["Angry","Enojado","/an-gri/"], ["Tired","Cansado","/tai-erd/"], ["Hungry","Hambriento","/jon-gri/"],
    ["Thirsty","Sediento","/zers-ti/"], ["Sick","Enfermo","/sik/"], ["Healthy","Saludable","/jel-zi/"], ["Clean","Limpio","/clin/"], ["Dirty","Sucio","/der-ti/"],
    ["Open","Abierto","/ou-pen/"], ["Closed","Cerrado","/clouzd/"], ["Full","Lleno","/ful/"], ["Empty","Vacío","/emp-ti/"], ["Right","Correcto/Derecha","/rait/"],
    ["Wrong","Incorrecto","/rong/"], ["Left","Izquierda","/left/"], ["Rich","Rico","/rich/"], ["Poor","Pobre","/pur/"], ["Expensive","Caro","/eks-pen-siv/"],
    ["Cheap","Barato","/chip/"], ["Red","Rojo","/red/"], ["Blue","Azul","/blu/"], ["Green","Verde","/grin/"], ["Yellow","Amarillo","/ye-lou/"],
    ["Black","Negro","/blak/"], ["White","Blanco","/uait/"], ["Brown","Café/Marrón","/braun/"], ["Orange","Naranja","/o-ranch/"], ["Pink","Rosa","/pink/"],
    ["Purple","Morado","/per-pol/"], ["Gray","Gris","/grei/"], ["Golden","Dorado","/goul-den/"], ["Silver","Plateado","/sil-ver/"], ["Clear","Claro","/clir/"]
  ]
};

// Vowel Pronunciation Examples (30 per vowel)
const vowelExamplesData = {
  A: [
    { short: "Cat", shortES: "Gato (A corta)", long: "Cake", longES: "Pastel (A larga)", shortPron: "/kæt/", longPron: "/keɪk/" },
    { short: "Hat", shortES: "Sombrero", long: "Hate", longES: "Odiar", shortPron: "/hæt/", longPron: "/heɪt/" },
    { short: "Sat", shortES: "Sentarse", long: "Safe", longES: "Seguro", shortPron: "/sæt/", longPron: "/seɪf/" },
    { short: "Pat", shortES: "Golpecito", long: "Page", longES: "Página", shortPron: "/pæt/", longPron: "/peɪdʒ/" },
    { short: "Bat", shortES: "Murciélago", long: "Base", longES: "Base", shortPron: "/bæt/", longPron: "/beɪs/" },
    { short: "Fat", shortES: "Gordo", long: "Fate", longES: "Destino", shortPron: "/fæt/", longPron: "/feɪt/" },
    { short: "Rat", shortES: "Rata", long: "Rate", longES: "Velocidad", shortPron: "/ræt/", longPron: "/reɪt/" },
    { short: "Tap", shortES: "Grifo", long: "Take", longES: "Tomar", shortPron: "/tæp/", longPron: "/teɪk/" },
    { short: "Max", shortES: "Máximo", long: "Make", longES: "Hacer", shortPron: "/mæks/", longPron: "/meɪk/" },
    { short: "Wax", shortES: "Cera", long: "Wake", longES: "Despertar", shortPron: "/wæks/", longPron: "/weɪk/" },
    { short: "Vat", shortES: "Tanque", long: "Wave", longES: "Onda", shortPron: "/væt/", longPron: "/weɪv/" },
    { short: "Man", shortES: "Hombre", long: "Mane", longES: "Crin", shortPron: "/mæn/", longPron: "/meɪn/" },
    { short: "Plan", shortES: "Plan", long: "Plane", longES: "Avión", shortPron: "/plæn/", longPron: "/pleɪn/" },
    { short: "Tan", shortES: "Bronceado", long: "Lane", longES: "Carril", shortPron: "/tæn/", longPron: "/leɪn/" },
    { short: "Can", shortES: "Lata", long: "Cane", longES: "Bastón", shortPron: "/kæn/", longPron: "/keɪn/" },
    { short: "Van", shortES: "Furgoneta", long: "Vane", longES: "Veleta", shortPron: "/væn/", longPron: "/veɪn/" },
    { short: "Map", shortES: "Mapa", long: "Mail", longES: "Correo", shortPron: "/mæp/", longPron: "/meɪl/" },
    { short: "Bag", shortES: "Bolsa", long: "Bake", longES: "Hornear", shortPron: "/bæg/", longPron: "/beɪk/" },
    { short: "Tag", shortES: "Etiqueta", long: "Game", longES: "Juego", shortPron: "/tæg/", longPron: "/ɡeɪm/" },
    { short: "Gag", shortES: "Chiste", long: "Gate", longES: "Puerta", shortPron: "/ɡæɡ/", longPron: "/ɡeɪt/" },
    { short: "Rag", shortES: "Trapo", long: "Rake", longES: "Rastrillo", shortPron: "/ræɡ/", longPron: "/reɪk/" },
    { short: "Jab", shortES: "Puño", long: "Jane", longES: "Nombre", shortPron: "/dʒæb/", longPron: "/dʒeɪn/" },
    { short: "Lab", shortES: "Laboratorio", long: "Late", longES: "Tarde", shortPron: "/læb/", longPron: "/leɪt/" },
    { short: "Nap", shortES: "Siesta", long: "Name", longES: "Nombre", shortPron: "/næp/", longPron: "/neɪm/" },
    { short: "Gap", shortES: "Brecha", long: "Gate", longES: "Puerta", shortPron: "/ɡæp/", longPron: "/ɡeɪt/" },
    { short: "Lap", shortES: "Regazo", long: "Late", longES: "Tarde", shortPron: "/læp/", longPron: "/leɪt/" },
    { short: "Jam", shortES: "Mermelada", long: "James", longES: "Nombre", shortPron: "/dʒæm/", longPron: "/dʒeɪmz/" },
    { short: "Ham", shortES: "Jamón", long: "Have", longES: "Tener", shortPron: "/hæm/", longPron: "/hæv/" },
    { short: "Dam", shortES: "Presa", long: "Date", longES: "Fecha", shortPron: "/dæm/", longPron: "/deɪt/" },
    { short: "Sam", shortES: "Nombre", long: "Same", longES: "Igual", shortPron: "/sæm/", longPron: "/seɪm/" }
  ],
  E: [
    { short: "Bed", shortES: "Cama (E corta)", long: "Bee", longES: "Abeja (E larga)", shortPron: "/bed/", longPron: "/biː/" },
    { short: "Pet", shortES: "Mascota", long: "Pete", longES: "Nombre", shortPron: "/pet/", longPron: "/piːt/" },
    { short: "Wet", shortES: "Mojado", long: "Wheat", longES: "Trigo", shortPron: "/wet/", longPron: "/wiːt/" },
    { short: "Net", shortES: "Red", long: "Need", longES: "Necesitar", shortPron: "/net/", longPron: "/niːd/" },
    { short: "Get", shortES: "Obtener", long: "Gene", longES: "Gen", shortPron: "/ɡet/", longPron: "/dʒiːn/" },
    { short: "Set", shortES: "Conjunto", long: "Seen", longES: "Visto", shortPron: "/set/", longPron: "/siːn/" },
    { short: "Let", shortES: "Permitir", long: "Lean", longES: "Delgado", shortPron: "/let/", longPron: "/liːn/" },
    { short: "Met", shortES: "Conocí", long: "Mean", longES: "Significar", shortPron: "/met/", longPron: "/miːn/" },
    { short: "Bet", shortES: "Apuesta", long: "Bean", longES: "Frijol", shortPron: "/bet/", longPron: "/biːn/" },
    { short: "Jet", shortES: "Chorro", long: "Jeans", longES: "Jeans", shortPron: "/dʒet/", longPron: "/dʒiːnz/" },
    { short: "Ten", shortES: "Diez", long: "Teen", longES: "Adolescente", shortPron: "/ten/", longPron: "/tiːn/" },
    { short: "Pen", shortES: "Pluma", long: "Peen", longES: "Cabeza de martillo", shortPron: "/pen/", longPron: "/piːn/" },
    { short: "Hen", shortES: "Gallina", long: "Heel", longES: "Talón", shortPron: "/hen/", longPron: "/hiːl/" },
    { short: "Men", shortES: "Hombres", long: "Me", longES: "Yo (objeto)", shortPron: "/men/", longPron: "/miː/" },
    { short: "Den", shortES: "Guarida", long: "Dean", longES: "Decano", shortPron: "/den/", longPron: "/diːn/" },
    { short: "Desk", shortES: "Escritorio", long: "Keep", longES: "Mantener", shortPron: "/desk/", longPron: "/kiːp/" },
    { short: "Pes", shortES: "Pies", long: "Peace", longES: "Paz", shortPron: "/pes/", longPron: "/piːs/" },
    { short: "Rest", shortES: "Descanso", long: "Reach", longES: "Alcanzar", shortPron: "/rest/", longPron: "/riːtʃ/" },
    { short: "Mess", shortES: "Desorden", long: "Feast", longES: "Banquete", shortPron: "/mes/", longPron: "/fiːst/" },
    { short: "Less", shortES: "Menos", long: "Lease", longES: "Arrendar", shortPron: "/les/", longPron: "/liːs/" },
    { short: "Best", shortES: "Mejor", long: "Beast", longES: "Bestia", shortPron: "/best/", longPron: "/biːst/" },
    { short: "Test", shortES: "Prueba", long: "Tease", longES: "Burlar", shortPron: "/test/", longPron: "/tiːz/" },
    { short: "Vest", shortES: "Chaleco", long: "Lease", longES: "Alquiler", shortPron: "/vest/", longPron: "/liːs/" },
    { short: "Chest", shortES: "Pecho", long: "Please", longES: "Por favor", shortPron: "/tʃest/", longPron: "/pliːz/" },
    { short: "Nest", shortES: "Nido", long: "Else", longES: "Otro", shortPron: "/nest/", longPron: "/els/" },
    { short: "Pest", shortES: "Plaga", long: "Meet", longES: "Conocer", shortPron: "/pest/", longPron: "/miːt/" },
    { short: "Red", shortES: "Rojo", long: "Reed", longES: "Caña", shortPron: "/red/", longPron: "/riːd/" },
    { short: "Wed", shortES: "Casar", long: "Weed", longES: "Hierba", shortPron: "/wed/", longPron: "/wiːd/" },
    { short: "Fed", shortES: "Alimentó", long: "Feed", longES: "Alimentar", shortPron: "/fed/", longPron: "/fiːd/" },
    { short: "Led", shortES: "Guió", long: "Lead", longES: "Plomo", shortPron: "/led/", longPron: "/led/" }
  ],
  I: [
    { short: "Bit", shortES: "Poco (I corta)", long: "Bite", longES: "Morder (I larga)", shortPron: "/bɪt/", longPron: "/baɪt/" },
    { short: "Sit", shortES: "Sentarse", long: "Site", longES: "Sitio", shortPron: "/sɪt/", longPron: "/saɪt/" },
    { short: "Fit", shortES: "Encajar", long: "Fine", longES: "Bien", shortPron: "/fɪt/", longPron: "/faɪn/" },
    { short: "Pit", shortES: "Pozo", long: "Pie", longES: "Pastel", shortPron: "/pɪt/", longPron: "/paɪ/" },
    { short: "Hit", shortES: "Golpe", long: "Hide", longES: "Esconder", shortPron: "/hɪt/", longPron: "/haɪd/" },
    { short: "Kit", shortES: "Kit", long: "Kite", longES: "Cometa", shortPron: "/kɪt/", longPron: "/kaɪt/" },
    { short: "Lit", shortES: "Iluminado", long: "Lite", longES: "Ligero", shortPron: "/lɪt/", longPron: "/laɪt/" },
    { short: "Wit", shortES: "Ingenio", long: "Wine", longES: "Vino", shortPron: "/wɪt/", longPron: "/waɪn/" },
    { short: "Din", shortES: "Ruido", long: "Dine", longES: "Cenar", shortPron: "/dɪn/", longPron: "/daɪn/" },
    { short: "Tin", shortES: "Lata", long: "Time", longES: "Tiempo", shortPron: "/tɪn/", longPron: "/taɪm/" },
    { short: "Sin", shortES: "Pecado", long: "Sine", longES: "Seno", shortPron: "/sɪn/", longPron: "/saɪn/" },
    { short: "Pin", shortES: "Alfiler", long: "Pine", longES: "Pino", shortPron: "/pɪn/", longPron: "/paɪn/" },
    { short: "Win", shortES: "Ganar", long: "Wine", longES: "Vino", shortPron: "/wɪn/", longPron: "/waɪn/" },
    { short: "Fin", shortES: "Aleta", long: "Fine", longES: "Bien", shortPron: "/fɪn/", longPron: "/faɪn/" },
    { short: "Bin", shortES: "Contenedor", long: "Bind", longES: "Atar", shortPron: "/bɪn/", longPron: "/baɪnd/" },
    { short: "Kin", shortES: "Pariente", long: "Kind", longES: "Amable", shortPron: "/kɪn/", longPron: "/kaɪnd/" },
    { short: "Grin", shortES: "Sonrisa", long: "Grind", longES: "Moler", shortPron: "/ɡrɪn/", longPron: "/ɡraɪnd/" },
    { short: "Grit", shortES: "Gravilla", long: "Glide", longES: "Deslizar", shortPron: "/ɡrɪt/", longPron: "/ɡlaɪd/" },
    { short: "Flip", shortES: "Voltear", long: "Flight", longES: "Vuelo", shortPron: "/flɪp/", longPron: "/flaɪt/" },
    { short: "Grip", shortES: "Agarre", long: "Gripe", longES: "Resfriado", shortPron: "/ɡrɪp/", longPron: "/ɡraɪp/" },
    { short: "Drip", shortES: "Goteo", long: "Drive", longES: "Conducir", shortPron: "/drɪp/", longPron: "/draɪv/" },
    { short: "Trip", shortES: "Viaje", long: "Trice", longES: "Instante", shortPron: "/trɪp/", longPron: "/traɪs/" },
    { short: "Ship", shortES: "Barco", long: "Shine", longES: "Brillar", shortPron: "/ʃɪp/", longPron: "/ʃaɪn/" },
    { short: "Chip", shortES: "Chip", long: "Chipe", longES: "Pequeño", shortPron: "/tʃɪp/", longPron: "/tʃaɪp/" },
    { short: "Skip", shortES: "Saltar", long: "Skies", longES: "Cielos", shortPron: "/skɪp/", longPron: "/skaɪz/" },
    { short: "Slip", shortES: "Resbalón", long: "Slide", longES: "Deslizar", shortPron: "/slɪp/", longPron: "/slaɪd/" },
    { short: "Tip", shortES: "Propina", long: "Tie", longES: "Corbata", shortPron: "/tɪp/", longPron: "/taɪ/" },
    { short: "Zip", shortES: "Cierre", long: "Zipe", longES: "Cierre rápido", shortPron: "/zɪp/", longPron: "/zaɪp/" },
    { short: "Rip", shortES: "Rasgadura", long: "Rice", longES: "Arroz", shortPron: "/rɪp/", longPron: "/raɪs/" },
    { short: "Lip", shortES: "Labio", long: "Life", longES: "Vida", shortPron: "/lɪp/", longPron: "/laɪf/" }
  ],
  O: [
    { short: "Hot", shortES: "Caliente (O corta)", long: "Home", longES: "Casa (O larga)", shortPron: "/hɒt/", longPron: "/hoʊm/" },
    { short: "Not", shortES: "No", long: "Note", longES: "Nota", shortPron: "/nɒt/", longPron: "/noʊt/" },
    { short: "Got", shortES: "Obtuve", long: "Goat", longES: "Cabra", shortPron: "/ɡɒt/", longPron: "/ɡoʊt/" },
    { short: "Lot", shortES: "Lote", long: "Load", longES: "Carga", shortPron: "/lɒt/", longPron: "/loʊd/" },
    { short: "Dot", shortES: "Punto", long: "Dote", longES: "Dotar", shortPron: "/dɒt/", longPron: "/doʊt/" },
    { short: "Pot", shortES: "Olla", long: "Poke", longES: "Pinchar", shortPron: "/pɒt/", longPron: "/poʊk/" },
    { short: "Cot", shortES: "Cuna", long: "Coat", longES: "Abrigo", shortPron: "/kɒt/", longPron: "/koʊt/" },
    { short: "Top", shortES: "Arriba", long: "Rope", longES: "Cuerda", shortPron: "/tɒp/", longPron: "/roʊp/" },
    { short: "Rot", shortES: "Podrirse", long: "Role", longES: "Rol", shortPron: "/rɒt/", longPron: "/roʊl/" },
    { short: "Box", shortES: "Caja", long: "Bone", longES: "Hueso", shortPron: "/bɒks/", longPron: "/boʊn/" },
    { short: "Fox", shortES: "Zorro", long: "Fore", longES: "Delante", shortPron: "/fɒks/", longPron: "/fɔːr/" },
    { short: "Lock", shortES: "Cerradura", long: "Lobe", longES: "Lóbulo", shortPron: "/lɒk/", longPron: "/loʊb/" },
    { short: "Mock", shortES: "Burlarse", long: "Mode", longES: "Modo", shortPron: "/mɒk/", longPron: "/moʊd/" },
    { short: "Rock", shortES: "Roca", long: "Rose", longES: "Rosa", shortPron: "/rɒk/", longPron: "/roʊz/" },
    { short: "Sock", shortES: "Calcetín", long: "Some", longES: "Alguno", shortPron: "/sɒk/", longPron: "/sʌm/" },
    { short: "Knock", shortES: "Golpe", long: "Node", longES: "Nodo", shortPron: "/nɒk/", longPron: "/noʊd/" },
    { short: "Clock", shortES: "Reloj", long: "Cloak", longES: "Capa", shortPron: "/klɒk/", longPron: "/kloʊk/" },
    { short: "Block", shortES: "Bloque", long: "Boat", longES: "Bote", shortPron: "/blɒk/", longPron: "/boʊt/" },
    { short: "Stock", shortES: "Existencias", long: "Smoke", longES: "Humo", shortPron: "/stɒk/", longPron: "/smoʊk/" },
    { short: "Shock", shortES: "Shock", long: "Slope", longES: "Pendiente", shortPron: "/ʃɒk/", longPron: "/sloʊp/" },
    { short: "Hog", shortES: "Cerdo", long: "Hope", longES: "Esperanza", shortPron: "/hɒɡ/", longPron: "/hoʊp/" },
    { short: "Log", shortES: "Tronco", long: "Lone", longES: "Solo", shortPron: "/lɒɡ/", longPron: "/loʊn/" },
    { short: "Dog", shortES: "Perro", long: "Dole", longES: "Repartir", shortPron: "/dɒɡ/", longPron: "/doʊl/" },
    { short: "Fog", shortES: "Niebla", long: "Fore", longES: "Delante", shortPron: "/fɒɡ/", longPron: "/fɔːr/" },
    { short: "Jog", shortES: "Trotar", long: "Joke", longES: "Broma", shortPron: "/dʒɒɡ/", longPron: "/dʒoʊk/" },
    { short: "Nod", shortES: "Asentir", long: "Node", longES: "Nodo", shortPron: "/nɒd/", longPron: "/noʊd/" },
    { short: "Pod", shortES: "Vaina", long: "Poke", longES: "Pinchar", shortPron: "/pɒd/", longPron: "/poʊk/" },
    { short: "Sod", shortES: "Césped", long: "Sole", longES: "Suela", shortPron: "/sɒd/", longPron: "/soʊl/" },
    { short: "Rod", shortES: "Vara", long: "Rode", longES: "Cabalgó", shortPron: "/rɒd/", longPron: "/roʊd/" },
    { short: "Cod", shortES: "Bacalao", long: "Code", longES: "Código", shortPron: "/kɒd/", longPron: "/koʊd/" }
  ],
  U: [
    { short: "Cut", shortES: "Cortar (U corta)", long: "Cute", longES: "Bonito (U larga)", shortPron: "/kʌt/", longPron: "/kjuːt/" },
    { short: "Nut", shortES: "Nuez", long: "Mute", longES: "Mudo", shortPron: "/nʌt/", longPron: "/mjuːt/" },
    { short: "But", shortES: "Pero", long: "Mule", longES: "Mula", shortPron: "/bʌt/", longPron: "/mjuːl/" },
    { short: "Put", shortES: "Poner", long: "Puke", longES: "Vomitar", shortPron: "/pʊt/", longPron: "/pjuːk/" },
    { short: "Hut", shortES: "Cabaña", long: "Huge", longES: "Enorme", shortPron: "/hʌt/", longPron: "/hjuːdʒ/" },
    { short: "Rut", shortES: "Surco", long: "Rule", longES: "Regla", shortPron: "/rʌt/", longPron: "/ruːl/" },
    { short: "Gut", shortES: "Intestino", long: "Rude", longES: "Grosero", shortPron: "/ɡʌt/", longPron: "/ruːd/" },
    { short: "Tub", shortES: "Bañera", long: "Tube", longES: "Tubo", shortPron: "/tʌb/", longPron: "/tjuːb/" },
    { short: "Rub", shortES: "Frotar", long: "Rude", longES: "Grosero", shortPron: "/rʌb/", longPron: "/ruːd/" },
    { short: "Hub", shortES: "Centro", long: "Huge", longES: "Enorme", shortPron: "/hʌb/", longPron: "/hjuːdʒ/" },
    { short: "Duh", shortES: "¡Obvio!", long: "Duke", longES: "Duque", shortPron: "/dʌ/", longPron: "/djuːk/" },
    { short: "Bum", shortES: "Trasero", long: "Fume", longES: "Humo", shortPron: "/bʌm/", longPron: "/fjuːm/" },
    { short: "Sum", shortES: "Suma", long: "June", longES: "Junio", shortPron: "/sʌm/", longPron: "/dʒuːn/" },
    { short: "Gum", shortES: "Chicle", long: "Tune", longES: "Canción", shortPron: "/ɡʌm/", longPron: "/tjuːn/" },
    { short: "Drum", shortES: "Tambor", long: "Dune", longES: "Duna", shortPron: "/drʌm/", longPron: "/djuːn/" },
    { short: "Gun", shortES: "Arma", long: "Guest", longES: "Invitado", shortPron: "/ɡʌn/", longPron: "/ɡest/" },
    { short: "Run", shortES: "Correr", long: "Rune", longES: "Runa", shortPron: "/rʌn/", longPron: "/ruːn/" },
    { short: "Sun", shortES: "Sol", long: "Sure", longES: "Seguro", shortPron: "/sʌn/", longPron: "/ʃʊr/" },
    { short: "Bun", shortES: "Bollo", long: "Brute", longES: "Bruto", shortPron: "/bʌn/", longPron: "/bruːt/" },
    { short: "Fun", shortES: "Diversión", long: "Fuse", longES: "Fusible", shortPron: "/fʌn/", longPron: "/fjuːz/" },
    { short: "Rug", shortES: "Alfombra", long: "Ruse", longES: "Treta", shortPron: "/rʌɡ/", longPron: "/ruːz/" },
    { short: "Bug", shortES: "Bicho", long: "Blue", longES: "Azul", shortPron: "/bʌɡ/", longPron: "/bluː/" },
    { short: "Dug", shortES: "Cavó", long: "Duke", longES: "Duque", shortPron: "/dʌɡ/", longPron: "/djuːk/" },
    { short: "Hug", shortES: "Abrazo", long: "Huge", longES: "Enorme", shortPron: "/hʌɡ/", longPron: "/hjuːdʒ/" },
    { short: "Mug", shortES: "Taza", long: "Muse", longES: "Musa", shortPron: "/mʌɡ/", longPron: "/mjuːz/" },
    { short: "Tug", shortES: "Tirón", long: "Tune", longES: "Canción", shortPron: "/tʌɡ/", longPron: "/tjuːn/" },
    { short: "Jug", shortES: "Jarra", long: "June", longES: "Junio", shortPron: "/dʒʌɡ/", longPron: "/dʒuːn/" },
    { short: "Cup", shortES: "Taza", long: "Cure", longES: "Curar", shortPron: "/kʌp/", longPron: "/kjʊr/" },
    { short: "Sup", shortES: "¿Qué tal?", long: "Suite", longES: "Suite", shortPron: "/sʌp/", longPron: "/swiːt/" },
    { short: "Pup", shortES: "Cachorro", long: "Puke", longES: "Vomitar", shortPron: "/pʌp/", longPron: "/pjuːk/" }
  ]
};

// Conjugations Data
const conjugationsData = {
  toBe: [
    { pronoun: "I", present: "am", past: "was", meaning: "Yo soy/estoy", example: "I am happy" },
    { pronoun: "You", present: "are", past: "were", meaning: "Tú eres/estás", example: "You are smart" },
    { pronoun: "He/She/It", present: "is", past: "was", meaning: "Él/Ella es/está", example: "He is good" },
    { pronoun: "We/They", present: "are", past: "were", meaning: "Nosotros/Ellos son/están", example: "They are ready" }
  ],
  doDoesId: [
    { pronoun: "I", presentPositive: "do", presentNegative: "don't", pastPositive: "did", pastNegative: "didn't", meaning: "Yo hago", example: "I do my homework" },
    { pronoun: "You", presentPositive: "do", presentNegative: "don't", pastPositive: "did", pastNegative: "didn't", meaning: "Tú haces", example: "You do a great job" },
    { pronoun: "He/She/It", presentPositive: "does", presentNegative: "doesn't", pastPositive: "did", pastNegative: "didn't", meaning: "Él/Ella hace", example: "She does the dishes" },
    { pronoun: "We/They", presentPositive: "do", presentNegative: "don't", pastPositive: "did", pastNegative: "didn't", meaning: "Nosotros/Ellos hacen", example: "We do sports" }
  ],
  negations: [
    { type: "don't", usage: "I, You, We, They (Presente)", spanish: "No hago/haces/hacemos/hacen", example: "I don't like coffee", exampleEs: "No me gusta el café" },
    { type: "doesn't", usage: "He, She, It (Presente)", spanish: "No hace", example: "She doesn't live here", exampleEs: "Ella no vive aquí" },
    { type: "didn't", usage: "Todos (Pasado)", spanish: "No hice/hiciste/hizo/hicimos/hicieron", example: "I didn't go home", exampleEs: "Yo no fui a casa" }
  ]
};

// 50 Verbs (Irregular and Regular separated)
const verbsData = [
  // Irregular
  ["Ir", "Go", "Went", "Gon", "/gou/ /uent/"], 
  ["Tener", "Have", "Had", "Jav", "/jav/ /jad/"],
  ["Hacer (Tarea)", "Do", "Did", "Du", "/du/ /did/"],
  ["Hacer (Crear)", "Make", "Made", "Meik", "/meik/ /meid/"],
  ["Decir", "Say", "Said", "Sei", "/sei/ /sed/"],
  ["Ver", "See", "Saw", "Si", "/si/ /so/"],
  ["Saber/Conocer", "Know", "Knew", "Nou", "/nou/ /niu/"],
  ["Tomar/Llevar", "Take", "Took", "Teik", "/teik/ /tuk/"],
  ["Pensar", "Think", "Thought", "Zink", "/zink/ /zot/"],
  ["Venir", "Come", "Came", "Com", "/com/ /keim/"],
  ["Dar", "Give", "Gave", "Giv", "/giv/ /geiv/"],
  ["Encontrar", "Find", "Found", "Faind", "/faind/ /faund/"],
  ["Decir/Contar", "Tell", "Told", "Tel", "/tel/ /tould/"],
  ["Convertirse", "Become", "Became", "Bi-com", "/bi-com/ /bi-keim/"],
  ["Dejar/Salir", "Leave", "Left", "Liv", "/liv/ /left/"],
  ["Sentir", "Feel", "Felt", "Fil", "/fil/ /felt/"],
  ["Poner", "Put", "Put", "Put", "/put/"],
  ["Traer", "Bring", "Brought", "Bring", "/bring/ /brot/"],
  ["Comenzar", "Begin", "Began", "Bi-gin", "/bi-gin/ /bi-gan/"],
  ["Mantener", "Keep", "Kept", "Kip", "/kip/ /kept/"],
  ["Sostener", "Hold", "Held", "Jold", "/jould/ /jeld/"],
  ["Escribir", "Write", "Wrote", "Rait", "/rait/ /rout/"],
  ["Hablar", "Speak", "Spoke", "Spik", "/spik/ /spouk/"],
  ["Escuchar (Oír)", "Hear", "Heard", "Jir", "/jir/ /jerd/"],
  ["Comer", "Eat", "Ate", "It", "/it/ /eit/"],
  ["Beber", "Drink", "Drank", "Drink", "/drink/ /drank/"],
  ["Correr", "Run", "Ran", "Ron", "/ron/ /ran/"],
  ["Dormir", "Sleep", "Slept", "Slip", "/slip/ /slept/"],
  ["Comprar", "Buy", "Bought", "Bai", "/bai/ /bot/"],
  ["Pagar", "Pay", "Paid", "Pei", "/pei/ /peid/"],

  // Regular (add -ed)
  ["Querer", "Want", "Wanted", "Uont", "/uont/ /uon-ted/"],
  ["Necesitar", "Need", "Needed", "Nid", "/nid/ /ni-ded/"],
  ["Trabajar", "Work", "Worked", "Uerk", "/uerk/ /uerkt/"],
  ["Mirar", "Look", "Looked", "Luk", "/luk/ /lukt/"],
  ["Usar", "Use", "Used", "Yus", "/yus/ /yuzd/"],
  ["Ayudar", "Help", "Helped", "Jelp", "/jelp/ /jelpt/"],
  ["Jugar", "Play", "Played", "Plei", "/plei/ /pleid/"],
  ["Llamar", "Call", "Called", "Col", "/col/ /cold/"],
  ["Intentar", "Try", "Tried", "Trai", "/trai/ /traid/"],
  ["Preguntar", "Ask", "Asked", "Ask", "/ask/ /askt/"],
  ["Caminar", "Walk", "Walked", "Uok", "/uok/ /uokt/"],
  ["Amar", "Love", "Loved", "Lov", "/lov/ /lovd/"],
  ["Gustar", "Like", "Liked", "Laik", "/laik/ /laikt/"],
  ["Recordar", "Remember", "Remembered", "Ri-mem-ber", "/ri-mem-ber/"],
  ["Mover", "Move", "Moved", "Muv", "/muv/ /muvd/"],
  ["Creer", "Believe", "Believed", "Bi-liv", "/bi-liv/"],
  ["Pasar", "Happen", "Happened", "Ja-pen", "/ja-pen/"],
  ["Esperar", "Wait", "Waited", "Ueit", "/ueit/ /uei-ted/"],
  ["Vivir", "Live", "Lived", "Liv", "/liv/ /livd/"],
  ["Aprender", "Learn", "Learned", "Lern", "/lern/ /lernd/"]
];

const modalsData = [
  ["Quisiera (Hacer algo)", "Would like", "/wuld laik/"],
  ["Me gustaría", "I would like", "/ai wuld laik/"],
  ["Poder (Habilidad/Permiso)", "Can", "/kan/"],
  ["Podría", "Could", "/kuld/"],
  ["Debería (Consejo)", "Should", "/shuld/"],
  ["Debo (Obligación)", "Must", "/most/"],
  ["Querer", "Want to", "/wont tu/"],
  ["Necesitar", "Need to", "/nid tu/"],
  ["Tengo que", "Have to", "/jav tu/"],
  ["Estar a punto de/Ir a", "Going to", "/gou-ing tu/"]
];

const sentencesData = [
  ["Sujeto + Verbo + Objeto", "Regla de Oro: Siempre en este orden."],
  ["Yo quiero una manzana.", "I want an apple.", "/ai wont an a-pol/"],
  ["Tú necesitas agua.", "You need water.", "/yu nid wa-ter/"],
  ["Él tiene un perro grande.", "He has a big dog.", "/ji jas a big dog/"],
  ["Nosotros fuimos a la tienda.", "We went to the store.", "/wi went tu de stor/"],
  ["Ellos comieron pastel.", "They ate cake.", "/dei eit keik/"],
  ["A mí me gusta el azul.", "I like blue.", "/ai laik blu/"],
  ["A ella no le gusta el café.", "She doesn't like coffee.", "/shi do-sent laik co-fi/"],
  ["Yo no vi el carro.", "I didn't see the car.", "/ai di-dent si de kar/"],
  ["¿Acaso tienes dinero?", "Do you have money?", "/du yu jav mo-ni/"],
  ["¿Fuiste a trabajar?", "Did you go to work?", "/did yu gou tu uerk/"],
  ["Me gustaría una silla.", "I would like a chair.", "/ai wuld laik a cher/"],
  ["Yo puedo ayudarte.", "I can help you.", "/ai kan jelp yu/"],
  ["Tú deberías dormir más.", "You should sleep more.", "/yu shuld slip mor/"],
  ["El gato está en la cama.", "The cat is on the bed.", "/de kat is on de bed/"]
];
